#
# xinitrc hook
#

# Fix the keyboard 
$C_HOME/commands/setup-kb.sh

# Launch redshift
exec redshift &

urxvtd -q -f -o 

$C_HOME/commands/setup-background.sh
$C_HOME/commands/reload-xresources.sh

awesome -c $C_HOME/apps/awesome/rc.lua

