#!/bin/sh

# Add ~/bin to bin
export PATH=$HOME/bin/:$PATH

# Browser to be used by start-browser.sh and others
export BROWSER="chromium"

# EDITOR and VISUAL


export EDITOR="emacsclient"
export VISUAL="emacsclient"

# IO devices
export C_KEYBOARD="IBM_MODEL_M"

