#!/bin/sh

export LANG="en_US.UTF-8"
export C_HOME=$HOME/.customize/

# Add ~/bin
export PATH=$HOME/bin/:$PATH

# EDITOR and VISUAL
export EDITOR="emacsclient"
export VISUAL="emacsclient"

## per-client settings override globals

HOST=$(hostname)
source $C_HOME/config/PROFILE_$HOST

export XDG_CONFIG_HOME="$C_HOME/by-host/$HOST/dot-config"
