#!/bin/sh

# Add ~/bin to bin
export PATH=$HOME/bin/:$PATH

# Browser to be used by start-browser.sh and others

# we want the latest and greatest!
export BROWSER="firefox-aurora"
#export BROWSER="firefox"

# EDITOR and VISUAL


export EDITOR="emacsclient"
export VISUAL="emacsclient"

# IO devices
export C_KEYBOARD="ASUS_LAPTOP_KB"

