#!/bin/sh

export CUSTOMIZE_HOME=$HOME/.customize

# Add ~/bin to bin
export PATH=$HOME/bin/:$PATH

export EDITOR="emacsclient"
export VISUAL="emacsclient"

# Browser to be used by start-browser.sh and others
# Elrond is a mac so we use open
export BROWSER="open"


