# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[git_branch]
ignore_branches = ['master', 'main']

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[line_break]
disabled = true

[openstack]
disabled = true

[gcloud]
disabled = true
